default: &default
  adapter: postgresql
  pool: <%= ENV["DATABASE_POOL"] || 64 %>
  timeout: 5000
  encoding: utf-8
  user: postgres
  username: postgres
  password: 88888888
  port: 5432

development:
  <<: *default
  database: task

test:
  <<: *default
  database: task_test

production:
  <<: *default
  database: task
